	      		template2.querySelector('.prod-name').innerHTML = prod['name']
	      		template2.querySelector('.prod-description').innerHTML = prod['name']
	      		template2.querySelector('.prod-price-from').innerHTML = prod['name']
	      		template2.querySelector('.prod-price-to').innerHTML = prod['name']
	      		template2.querySelector('.prod-installment').innerHTML = prod['name']